### ISSUE TITLE
Topics to document

### ISSUE THREAD

**Issue by segfaultxavi** [OAI/Documentation#1]
**Edit**: I've changed the purpose of this issue so it is a container for topics that would be nice to have discussed in the docs.

1. **Start Here**:
   - [x] **Intended Audience**: Who should read this guide and why, what page to read depending on your goal.
   - [x] **Advantages of using OpenAPI**: Summary of benefits obtained by using automated tools.
1. **Introduction**: General overview, for context. Skippable.
   - [x] **What is an API**: APIs in the general case (local and remote), Specification through Documentation, Specification through a Description File (list of benefits), historical examples.
   - [x] **What is OpenAPI**: Definition, types of APIs it can describe, evolution from Swagger, list of benefits, link to [OpenAPI.Tools](http://openapi.tools)
1. **The OpenAPI Specification explained**: Describe the Specification in a more approachable way, with links to the actual document and constant references to the relevant Best Practices pages. Put advanced topics in this chapter to keep the TOC simple, but tag them clearly.
   - [x] **Basic structure**: Minimal Hello World API description.
   - [x] **Paths Object**:
   - [x] **Content**:
   - [x] **Parameters**:
   - [x] **Components**:
   - [x] **Servers**:
   - [x] **Documentation & Examples**:
   - [ ] **Callbacks and Webhooks** [Advanced]: What’s the difference, with examples.
   - [ ] **Schemas [Advanced]**: examples for schemas, responses and parameters.
   - [ ] **Security [Advanced]**: `securityScheme` and `security`.
1. **Best Practices**: Suggestions that greatly simplify working with the spec even though technically they do not belong to it.
   - [x] **Keep a single source of truth**: Always, no matter your workflow (Design-first, Code-first , ...).
   - [x] **How to write the description file**: By hand, Editors, Domain-Specific Languages, Code annotations.
   - [x] **Do not Repeat Yourself**: Reusing descriptions using `$ref`. Example directory structures.

**Comment by MikeRalphson** [comment]
Closing in favour of #59 - thanks all.
