### ISSUE TITLE
A site should be created for easy browsing of the documentation

### ISSUE THREAD

**Issue by mniinio** [OAI/Documentation#11]
Requirements from the TSC meeting:
- Accessible
- TOC always visible
- Clickable svg-files

**Comment by mniinio** [comment]
I forked this repo and created a site there. There are still a few accessibility issues to fix, mainly to put alternative texts to the SVG objects and to fix some default issues with the theme's accessibility (labels, and a few links).
I did need to do some changes to @Xavi’s stuff to get it work (svg files should be in object tags, not img and code blocks can't be inside html). The links now work in SVG but the *missing target=_blank* issue should be fixed in the .dot files, I know fixed it directly to SVG files beacuse I couldn't get the dot files converted.

**Comment by segfaultxavi** [comment]
Is there any way to have side by side code blocks?
I only tried with tables because I don't know any better.

**Comment by lornajane** [comment]
This looks to be in good shape! Nice work, people!

**Comment by mniinio** [comment]
Thanks @lornajane ! Some stuff still to be done, but most things done. @segfaultxavi the code side-by-side is possibly to do with CSS, it needs a bit of magic because of trying to avoid any extra HTML around the code blocks. And that magic is not entirely the recommended stuff for accessibility, even though it's standard HTML5, because older browsers and special readers etc. might not support it.

**Comment by ncaidin** [comment]
@mniinio , what technologies/workflow are you using? Is it still Github Pages? I notice Jekyll mentioned on the published page?

**Comment by mniinio** [comment]
@ncaidin it's just Github Pages. GH pages use internally Jekyll as site generator, it's built in. https://docs.github.com/en/github/working-with-github-pages/setting-up-a-github-pages-site-with-jekyll

**Comment by mniinio** [comment]
In order to get the fork working on this original repo, could someone with more access change the settings of the repo to activate the github pages please @ncaidin or @segfaultxavi

**Comment by ncaidin** [comment]
@webron could you please respond to @mniinio 's request for access change?

**Comment by webron** [comment]
I can activate github pages, just need to know on which branch and folder.

**Comment by mniinio** [comment]
Master branch and /root @webron

**Comment by mniinio** [comment]
@ncaidin @lornajane @segfaultxavi the new documentation site is now up and running. Still, some minor tweaks to be done, but I'll aim to get them done by the 3.1.0 launch (and at least list them in the issues). Site address https://oai.github.io/Documentation/
