### ISSUE TITLE
Table of contents is not in the correct order

### ISSUE THREAD

**Issue by segfaultxavi** [OAI/Documentation#13]
The proper order should be:
- Getting Started
- Introduction
- Specification Explained
- Best Practices

**Comment by mniinio** [comment]
There needs to be either a readme or an index.md file for the site to build. Either one needs to be also part of the TOC, else the site won't build. So I'm renaming start-here to index.md and removing readme

NOTE: The theme handles the TOC as dynamic, so once you click on a topic, the order changes (to the bottom). But after the changes are committed default order is correct.

Instructions to ordering pages (note the nav_order alone is enough for just reordering): https://pmarsceill.github.io/just-the-docs/docs/navigation-structure/#ordering-pages
