### ISSUE TITLE
The OpenAPI Specification Explained page has two Table of Contents

### ISSUE THREAD

**Issue by segfaultxavi** [OAI/Documentation#15]
I guess because `has_children == true` a TOC is automatically added by the theme, but it already has one, and it's more detailed. The automatic TOC should be removed.

**Comment by mniinio** [comment]
I removed the automatic TOC, but it removes it also from the side navigation. Also, it's not best practice to maintain a manual toc, since the links get broken really easily or a page gets missing...

**Comment by segfaultxavi** [comment]
Unfortunately, I don't think dropping this whole section from the TOC is acceptable.
I like the manual TOC because it contains more information than just the page titles. In this case, it shows which keywords are discussed in each page, which I think is pretty useful.
Isn't there a way to have the TOC appear on the sidebar but hide it from the page? In Sphinx I do that by marking the toc as `:hidden:` but I don't know about github pages.

**Comment by segfaultxavi** [comment]
Answering my own question, apparently adding `toc: false` to the frontmatter should do the trick. I haven't checked, though.
