### ISSUE TITLE
Some anchor tags are invalid

### ISSUE THREAD

**Issue by stelcodes** [OAI/Documentation#31]
Some anchor tags don't point to a valid `id` on the corresponding page like `https://spec.openapis.org/oas/v3.1.0#pathsObject`. It should be `https://spec.openapis.org/oas/v3.1.0#paths-object`. Seems like the `id`s were switched to kebab case but some links with anchor tags were not updated in this repo.

**Comment by mniinio** [comment]
This is identical to #30 where the issue is fixed, once someone with access rights merges the commit I just approved

**Comment by AdrianMachado** [comment]
I can go through and update the rest of the links in a followup to #30 if you'd like @mniinio ?

**Comment by mniinio** [comment]
@AdrianMachado that would be great, I'm quite stuck right now with other things

**Comment by AdrianMachado** [comment]
@mniinio all done, please review and merge

**Comment by mniinio** [comment]
@AdrianMachado I don't have merge rights to this repo, so pinging @segfaultxavi here and also in OAI getting started guide slack channel to merge these

**Comment by segfaultxavi** [comment]
I don't have time to properly review the PRs, but as long as they have been approved by @mniinio I'll merge them.
We should definitely give admin rights on this repo to somebody who is still involved in the OAI :)

Also, note that the svg files contain invalid links too!
