### ISSUE TITLE
Difficult to figure how to contribute to docs

### ISSUE THREAD

**Issue by meenakshi-dhanani** [OAI/Documentation#41]
https://oai.github.io/Documentation/start-here.html - I wanted to contribute/raise a PR for an edit on the documentation, but there is no link to a GitHub repository that would lead me here. If we're hoping for individuals to participate and contribute at least to the docs, typos or factual errors even, we could add a link to this GitHub repository.

It was two-step navigation for me personally. Let's make this easier for others?

For instance - there's an Edit button on the top of the page - https://code.visualstudio.com/docs/setup/setup-overview

![image](https://user-images.githubusercontent.com/14279061/175047205-886e88f2-eded-49bc-9a70-a1ede79ef4e4.png)

**Comment by MikeRalphson** [comment]
Possibly a [fork me on Github ribbon](https://github.blog/2008-12-19-github-ribbons/) would do the trick.

**Comment by MikeRalphson** [comment]
Went with a CSS only [solution](https://github.com/simonwhitaker/github-fork-ribbon-css).
