### ISSUE TITLE
Documentation Links Broken

### ISSUE THREAD

**Issue by umrigar** [OAI/Documentation#46]
All documentation links, including the "Getting Started" link on the homepage appear broken.

**Comment by MikeRalphson** [comment]
Thanks. I can see two broken links, for now can you use the left navigation menu?

**Comment by umrigar** [comment]
I can use the left nav, but I am still seeing broken links.  Examples:  [Getting Started](https://github.com/OAI/Documentation/blob/main/start-here.md) on [OAI Documentation Home Page](https://github.com/OAI/Documentation); [The Open API Specification explained](https://oai.github.io/Documentation/specification.md) on [Getting Started](https://oai.github.io/Documentation/) page. 
Thanks

**Comment by MikeRalphson** [comment]
Yes, I see those too, will check if local dev server shows the same problem.
