### ISSUE TITLE
tbarn:coc-enforcement-doc

### ISSUE THREAD

**Issue by Saud96525** [OAI/Documentation#60]

**Comment by Saud96525** [comment]
https://github.com/OAI/Documentation/issues/60#issue-1702810873

**Comment by Saud96525** [comment]
https://github.com/OAI/Documentation/issues/60#issue-1702810873

**Comment by Saud96525** [comment]
I want to add my Arabic language to facilitate the use

**Comment by Carinamaus** [comment]
Have a nice day 🙂
Greetings
